// Code generated by ogen, DO NOT EDIT.

package orderv1

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *GenericErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #
type BadGatewayError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadGatewayError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadGatewayError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadGatewayError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadGatewayError) SetMessage(val string) {
	s.Message = val
}

func (*BadGatewayError) cancelOrderRes()    {}
func (*BadGatewayError) createOrderRes()    {}
func (*BadGatewayError) getOrderByUuidRes() {}
func (*BadGatewayError) payOrderRes()       {}

// Ref: #
type ConflictError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ConflictError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ConflictError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ConflictError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ConflictError) SetMessage(val string) {
	s.Message = val
}

func (*ConflictError) cancelOrderRes() {}
func (*ConflictError) payOrderRes()    {}

// Ref: #
type GenericError struct {
	// HTTP-код ошибки.
	Code OptInt `json:"code"`
	// Описание ошибки.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *GenericError) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *GenericError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *GenericError) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *GenericError) SetMessage(val OptString) {
	s.Message = val
}

// GenericErrorStatusCode wraps GenericError with StatusCode.
type GenericErrorStatusCode struct {
	StatusCode int
	Response   GenericError
}

// GetStatusCode returns the value of StatusCode.
func (s *GenericErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *GenericErrorStatusCode) GetResponse() GenericError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GenericErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *GenericErrorStatusCode) SetResponse(val GenericError) {
	s.Response = val
}

// Ref: #
type NotFoundError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *NotFoundError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFoundError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NotFoundError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFoundError) SetMessage(val string) {
	s.Message = val
}

func (*NotFoundError) cancelOrderRes()    {}
func (*NotFoundError) getOrderByUuidRes() {}
func (*NotFoundError) payOrderRes()       {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPaymentMethod returns new OptPaymentMethod with value set to v.
func NewOptPaymentMethod(v PaymentMethod) OptPaymentMethod {
	return OptPaymentMethod{
		Value: v,
		Set:   true,
	}
}

// OptPaymentMethod is optional PaymentMethod.
type OptPaymentMethod struct {
	Value PaymentMethod
	Set   bool
}

// IsSet returns true if OptPaymentMethod was set.
func (o OptPaymentMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPaymentMethod) Reset() {
	var v PaymentMethod
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPaymentMethod) SetTo(v PaymentMethod) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPaymentMethod) Get() (v PaymentMethod, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPaymentMethod) Or(d PaymentMethod) PaymentMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTotalPriceMinor returns new OptTotalPriceMinor with value set to v.
func NewOptTotalPriceMinor(v TotalPriceMinor) OptTotalPriceMinor {
	return OptTotalPriceMinor{
		Value: v,
		Set:   true,
	}
}

// OptTotalPriceMinor is optional TotalPriceMinor.
type OptTotalPriceMinor struct {
	Value TotalPriceMinor
	Set   bool
}

// IsSet returns true if OptTotalPriceMinor was set.
func (o OptTotalPriceMinor) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTotalPriceMinor) Reset() {
	var v TotalPriceMinor
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTotalPriceMinor) SetTo(v TotalPriceMinor) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTotalPriceMinor) Get() (v TotalPriceMinor, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTotalPriceMinor) Or(d TotalPriceMinor) TotalPriceMinor {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #
type Order struct {
	// UUID заказа.
	OrderUUID uuid.UUID `json:"order_uuid"`
	// UUID пользователя.
	UserUUID uuid.UUID `json:"user_uuid"`
	// Список UUID деталей.
	PartUuids []uuid.UUID `json:"part_uuids"`
	// Сумма заказа в копейках.
	TotalPriceMinor OptInt64 `json:"total_price_minor"`
	// UUID транзакции.
	TransactionUUID OptUUID          `json:"transaction_uuid"`
	PaymentMethod   OptPaymentMethod `json:"payment_method"`
	Status          OrderStatus      `json:"status"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *Order) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *Order) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *Order) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// GetTotalPriceMinor returns the value of TotalPriceMinor.
func (s *Order) GetTotalPriceMinor() OptInt64 {
	return s.TotalPriceMinor
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *Order) GetTransactionUUID() OptUUID {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *Order) GetPaymentMethod() OptPaymentMethod {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *Order) GetStatus() OrderStatus {
	return s.Status
}

// SetOrderUUID sets the value of OrderUUID.
func (s *Order) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *Order) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *Order) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// SetTotalPriceMinor sets the value of TotalPriceMinor.
func (s *Order) SetTotalPriceMinor(val OptInt64) {
	s.TotalPriceMinor = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *Order) SetTransactionUUID(val OptUUID) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *Order) SetPaymentMethod(val OptPaymentMethod) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *Order) SetStatus(val OrderStatus) {
	s.Status = val
}

func (*Order) cancelOrderRes()    {}
func (*Order) getOrderByUuidRes() {}

// Ref: #
type OrderCreateRequest struct {
	UserUUID  UserUUID  `json:"user_uuid"`
	PartUuids PartUuids `json:"part_uuids"`
}

// GetUserUUID returns the value of UserUUID.
func (s *OrderCreateRequest) GetUserUUID() UserUUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *OrderCreateRequest) GetPartUuids() PartUuids {
	return s.PartUuids
}

// SetUserUUID sets the value of UserUUID.
func (s *OrderCreateRequest) SetUserUUID(val UserUUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *OrderCreateRequest) SetPartUuids(val PartUuids) {
	s.PartUuids = val
}

// Ref: #
type OrderCreateResponse struct {
	OrderUUID       OrderUUID          `json:"order_uuid"`
	TotalPriceMinor OptTotalPriceMinor `json:"total_price_minor"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *OrderCreateResponse) GetOrderUUID() OrderUUID {
	return s.OrderUUID
}

// GetTotalPriceMinor returns the value of TotalPriceMinor.
func (s *OrderCreateResponse) GetTotalPriceMinor() OptTotalPriceMinor {
	return s.TotalPriceMinor
}

// SetOrderUUID sets the value of OrderUUID.
func (s *OrderCreateResponse) SetOrderUUID(val OrderUUID) {
	s.OrderUUID = val
}

// SetTotalPriceMinor sets the value of TotalPriceMinor.
func (s *OrderCreateResponse) SetTotalPriceMinor(val OptTotalPriceMinor) {
	s.TotalPriceMinor = val
}

func (*OrderCreateResponse) createOrderRes() {}

// Ref: #
type OrderPayRequest struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *OrderPayRequest) GetPaymentMethod() PaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *OrderPayRequest) SetPaymentMethod(val PaymentMethod) {
	s.PaymentMethod = val
}

// Ref: #
type OrderPayResponse struct {
	// UUID транзакции.
	TransactionUUID string `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *OrderPayResponse) GetTransactionUUID() string {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *OrderPayResponse) SetTransactionUUID(val string) {
	s.TransactionUUID = val
}

func (*OrderPayResponse) payOrderRes() {}

// Статус заказа.
// Ref: #
type OrderStatus string

const (
	OrderStatusSTATUSPENDINGPAYMENT OrderStatus = "STATUS_PENDING_PAYMENT"
	OrderStatusSTATUSPAID           OrderStatus = "STATUS_PAID"
	OrderStatusSTATUSCANCELLED      OrderStatus = "STATUS_CANCELLED"
)

// AllValues returns all OrderStatus values.
func (OrderStatus) AllValues() []OrderStatus {
	return []OrderStatus{
		OrderStatusSTATUSPENDINGPAYMENT,
		OrderStatusSTATUSPAID,
		OrderStatusSTATUSCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderStatusSTATUSPENDINGPAYMENT:
		return []byte(s), nil
	case OrderStatusSTATUSPAID:
		return []byte(s), nil
	case OrderStatusSTATUSCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderStatus) UnmarshalText(data []byte) error {
	switch OrderStatus(data) {
	case OrderStatusSTATUSPENDINGPAYMENT:
		*s = OrderStatusSTATUSPENDINGPAYMENT
		return nil
	case OrderStatusSTATUSPAID:
		*s = OrderStatusSTATUSPAID
		return nil
	case OrderStatusSTATUSCANCELLED:
		*s = OrderStatusSTATUSCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type OrderUUID uuid.UUID

type PartUuids []uuid.UUID

// Способ оплаты.
// Ref: #
type PaymentMethod string

const (
	PaymentMethodPAYMENTMETHODUNSPECIFIED   PaymentMethod = "PAYMENT_METHOD_UNSPECIFIED"
	PaymentMethodPAYMENTMETHODCARD          PaymentMethod = "PAYMENT_METHOD_CARD"
	PaymentMethodPAYMENTMETHODSBP           PaymentMethod = "PAYMENT_METHOD_SBP"
	PaymentMethodPAYMENTMETHODCREDITCARD    PaymentMethod = "PAYMENT_METHOD_CREDIT_CARD"
	PaymentMethodPAYMENTMETHODINVESTORMONEY PaymentMethod = "PAYMENT_METHOD_INVESTOR_MONEY"
)

// AllValues returns all PaymentMethod values.
func (PaymentMethod) AllValues() []PaymentMethod {
	return []PaymentMethod{
		PaymentMethodPAYMENTMETHODUNSPECIFIED,
		PaymentMethodPAYMENTMETHODCARD,
		PaymentMethodPAYMENTMETHODSBP,
		PaymentMethodPAYMENTMETHODCREDITCARD,
		PaymentMethodPAYMENTMETHODINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case PaymentMethodPAYMENTMETHODUNSPECIFIED:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODCARD:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODSBP:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODCREDITCARD:
		return []byte(s), nil
	case PaymentMethodPAYMENTMETHODINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PaymentMethod) UnmarshalText(data []byte) error {
	switch PaymentMethod(data) {
	case PaymentMethodPAYMENTMETHODUNSPECIFIED:
		*s = PaymentMethodPAYMENTMETHODUNSPECIFIED
		return nil
	case PaymentMethodPAYMENTMETHODCARD:
		*s = PaymentMethodPAYMENTMETHODCARD
		return nil
	case PaymentMethodPAYMENTMETHODSBP:
		*s = PaymentMethodPAYMENTMETHODSBP
		return nil
	case PaymentMethodPAYMENTMETHODCREDITCARD:
		*s = PaymentMethodPAYMENTMETHODCREDITCARD
		return nil
	case PaymentMethodPAYMENTMETHODINVESTORMONEY:
		*s = PaymentMethodPAYMENTMETHODINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type TotalPriceMinor int64

type UserUUID uuid.UUID

// Ref: #
type ValidationError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ValidationError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ValidationError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ValidationError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ValidationError) SetMessage(val string) {
	s.Message = val
}

func (*ValidationError) cancelOrderRes()    {}
func (*ValidationError) createOrderRes()    {}
func (*ValidationError) getOrderByUuidRes() {}
func (*ValidationError) payOrderRes()       {}
