// Code generated by ogen, DO NOT EDIT.

package orderv1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOrder implements cancelOrder operation.
	//
	// Cancels an existing order.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	CancelOrder(ctx context.Context, params CancelOrderParams) (CancelOrderRes, error)
	// CreateOrder implements createOrder operation.
	//
	// Creates a new order.
	//
	// POST /api/v1/orders
	CreateOrder(ctx context.Context, req *OrderCreateRequest) (CreateOrderRes, error)
	// GetOrderByUuid implements getOrderByUuid operation.
	//
	// Retrieves order details by UUID.
	//
	// GET /api/v1/orders/{order_uuid}
	GetOrderByUuid(ctx context.Context, params GetOrderByUuidParams) (GetOrderByUuidRes, error)
	// PayOrder implements payOrder operation.
	//
	// Processes payment for an existing order.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	PayOrder(ctx context.Context, req *OrderPayRequest, params PayOrderParams) (PayOrderRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
